spring:
  datasource:
    url: "jdbc:mysql://${IP:192.168.99.100}: ${PORT:8888}/${DATABASENAME:sakila}?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 页面热加载
  thymeleaf:
    cache: false
  # 环境端口
  profiles:
    active: prod
  # 安全配置
  security:
    user:
      name: root
      password: root

management:
  endpoints:
    web:
      # 暴露endpoint
      exposure:
        include: "*"
    shutdown:
        # 启用shutdown
        enabled: true
        # 禁用密码验证
        sensitive: true
# 日志生成
logging:
  file: exam1.log
  level:
    org:
      srpingframework:
        web: DEBUG